title: OZIproject.dev
description: Homepage for the OZI Project - A semantic approach to packaging Python projects with Meson.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
