title: OZIproject.dev
description: '
  <div class="mobile">
    <a href="https://www.oziproject.dev/" aria-labelledby="primary-navigation">
      <img src="assets/brand/images/ozi_logo_v2.png" width="24" alt="Small OZI Icon for mobile users.">
    </a>
    <h1 id="primary-navigation">OZI Project</h1>
    <input class="side-menu" type="checkbox" id="side-menu"/>
    <label class="hamb" for="side-menu" tabindex=0" id="hamb-menu-btn">
      <span class="hamb-line"></span>
    </label>
    <script src="/assets/js/accessibility.js"></script>
    <nav class="nav">
      <ul class="menu">
        <li tabindex=0 class="menu-item"><a href="https://docs.oziproject.dev/en/stable/" alt="Documentation"></a></li>
        <li tabindex=0 class="menu-item"><a href="https://pypi.org/project/OZI">View on PyPI</a></li>
        <li tabindex=0 class="menu-item"><a href="https://github.com/orgs/OZI-Project/discussions">Join the Discussion</a></li>
        <li tabindex=0 class="menu-item"><a href="https://www.patreon.com/OZIProject">Fund Development</a></li>
      </ul>
    </nav>
  </div>
  <a href="https://no-ai-icon.com/statement/?url=oziproject.dev"><img src="assets/brand/no-ai-icon-01.svg" class="icon-info" width=72px></a>'
logo: assets/brand/images/ozi_social_logo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true
github:
  is_project_page: true
  owner_url: https://github.com/rjdbcm
  owner_name: Eden Rose
  repository_url: https://github.com/OZI-Project/OZI
  tar_url: https://github.com/OZI-Project/OZI/tarball/main
  zip_url: https://github.com/OZI-Project/OZI/zipball/main
