title: OZIproject.dev
description: '
  <div class="mobile">
    <a href="https://www.oziproject.dev/" aria-labelledby="primary-navigation">
      <img src="ozi_logo_v2.png" width="28" alt="Small OZI Icon for mobile users.">
    </a>
    <h1 id="primary-navigation">OZIproject.dev</h1>
    <small>Python Packaging for Meson &dagger;</small>
    <input class="side-menu" type="checkbox" id="side-menu"/>
    <label class="hamb" for="side-menu" tabindex=0" id="hamb-menu-btn">
      <span class="hamb-line"></span>
    </label>
    <script src="/assets/js/accessibility.js"></script>
    <nav class="nav">
      <ul class="menu">
        <li tabindex=0 class="menu-item"><a href="https://docs.oziproject.dev/">docs.OZIproject.dev Documentation</a></li>
        <li tabindex=0 class="menu-item"><a href="/blog.html">Blog</a></li>
        <li tabindex=0 class="menu-item"><a href="/media.html">Media</a></li>
        <li tabindex=0 class="menu-item"><a href="/monitoring.html">Monitoring</a></li>
        <li tabindex=0 class="menu-item"><a href="https://ko-fi.com/N4N7QZYMN" target="_blank">
            <img height="36" style="border:0px;height:36px;" src="https://storage.ko-fi.com/cdn/kofi2.png?v=3" border="0" alt="Support the OZI Project" />
          </a>
        </li>
      </ul>
    </nav>
  </div>
  <hr>
  <small>
    &dagger; <a href="https://mesonbuild.com/">Meson</a> is a registered trademark of 
    Jussi Pakkanen. The OZI project is not affiliated with or endorsed by the Meson 
    development team or Jussi Pakkanen.
  </small>'
logo: ozi_social_logo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
