title: OZIproject.dev
description: '
  <div class="mobile">
    <a href="https://www.oziproject.dev/" aria-labelledby="primary-navigation">
      <img src="ozi_logo_v2.png" width="28" alt="Small OZI Icon for mobile users.">
    </a>
    <h1 id="primary-navigation">OZIproject.dev</h1>
    <small>Python Project Packaging for Meson &dagger;</small>
    <input class="side-menu" type="checkbox" id="side-menu"/>
    <label class="hamb" for="side-menu" tabindex=0" id="hamb-menu-btn">
      <span class="hamb-li<pne"></span>
    </label>
    <script src="/assets/js/accessibility.js"></script>
    <nav class="nav">
      <ul class="menu">
        <li tabindex=0 class="menu-item"><a href="https://docs.oziproject.dev/"></a></li>
        <li tabindex=0 class="menu-item"><a href="https://pypi.org/project/OZI">Install OZI</a></li>
        <li tabindex=0 class="menu-item"><a href="https://github.com/orgs/OZI-Project/discussions">Talk to Us</a></li>
        <li tabindex=0 class="menu-item"><a href="https://www.patreon.com/OZIProject">Fund OZI</a></li>
      </ul>
    </nav>
  </div>
  <a href="https://github.com/OZI-Project" alt="Button">
    <img src="https://raw.githubusercontent.com/OZI-Project/.github/main/github-metrics-ozi-project.svg">
  </a>'
logo: ozi_social_logo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true
github:
  is_project_page: false
  repository_url: https://github.com/OZI-Project/OZI
  tar_url: https://github.com/OZI-Project/OZI/tarball/main
  zip_url: https://github.com/OZI-Project/OZI/zipball/main
