title: OZIproject.dev
description: '<small>
  &dagger; Meson is a registered trademark of Jussi Pakkanen. The OZI
  project is not affiliated with or endorsed by the Meson development team or Jussi Pakkanen.
  </small>
  <p><a href="/blog.html">Blog</a></p>
  <p><a href="/media.html">Media</a></p>
  <p><a href="/monitoring.html">Monitoring</a></p>'
logo: ozi_social_logo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
