title: OZIproject.dev
description: '
  <div class="mobile">
    <a href="https://www.oziproject.dev/" aria-labelledby="primary-navigation">
      <img src="ozi_logo_v2.png" width="28" alt="Small OZI Icon for mobile users.">
    </a>
    <h1 id="primary-navigation">OZIproject.dev</h1>
    <small>Python Packaging for Meson &dagger;</small>
    <input class="side-menu" type="checkbox" id="side-menu"/>
    <label class="hamb" for="side-menu" tabindex=0
      onkeydown = "if (event.keyCode == 13) document.getElementById('side-menu').click()">
      <span class="hamb-line"></span>
    </label>
    <nav class="nav">
      <ul class="menu">
        <li><a href="https://docs.oziproject.dev/">docs.OZIproject.dev Documentation</a></li>
        <li><a href="/blog.html">Blog</a></li>
        <li><a href="/media.html">Media</a></li>
        <li><a href="/monitoring.html">Monitoring</a></li>
      </ul>
    </nav>
  </div>
  <hr>
  <small>
    &dagger; <a href="https://mesonbuild.com/">Meson</a> is a registered trademark of 
    Jussi Pakkanen. The OZI project is not affiliated with or endorsed by the Meson 
    development team or Jussi Pakkanen.
  </small>'
logo: ozi_social_logo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
