on:
    schedule:
      - cron: '0 0 * * 0,1,2,3,4,5,6'
    workflow_dispatch:

permissions:
  contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        steps:

            - name: Harden Runner
              uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
              with:
                egress-policy: audit

            - uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
              with:
               python-version: '3.12'

            - name: Update api.json metadata
              run: |
                python -m pip install --upgrade pip
                python -m pip install OZI
                ozi -i > api.json

            - name: Commit api.json changes
              continue-on-error: true
              run: |
                git config --global user.name 'OZI-Project'
                git config --global user.email 'OZI-Project@users.noreply.github.com'
                git commit -am "API endpoint updated"
                git push

            - name: Info
              run: |
                echo "fromJson($( curl -L https://oziproject.dev/api.json | jq -c '.prerelease' ))"
