on:
    schedule:
      - cron: '0 0 * * 0,1,2,3,4,5,6'

permissions:
  contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        steps:

            - name: Harden Runner
              uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit

            - name: Set up Python 3.12
              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
              with:
               cache: 'pip'
               python-version: '3.12'

            - name: Update OZI API metadata
              run: |
                python -m pip install --upgrade pip
                python -m pip install OZI
                python -c 'import json;from ozi import metadata;f=open("api.json", "w");json.dump(metadata, f, indent=2);f.close()'
