on:
    # schedule:
    #   - cron: '0 0 * * 0,1,2,3,4,5,6'
    workflow_dispatch:

permissions:
  contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:

            - name: Harden Runner
              uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
              with:
                egress-policy: audit

            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
              with:
               python-version: '3.12'

            - name: Update api.json metadata
              run: |
                python -m pip install --upgrade pip
                python -m pip install OZI
                out=$(ozi -i | jq --compact-output) && echo "$out" > api.json

            - name: Commit api.json changes
              continue-on-error: true
              run: |
                git config --global user.name 'OZI-Project'
                git config --global user.email 'OZI-Project@users.noreply.github.com'
                git commit -am "API endpoint updated"
                git push
