on:
    schedule:
      - cron: '0 0 * * 0,1,2,3,4,5,6'
    workflow_dispatch:

permissions:
  contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:

            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
              with:
               python-version: '3.12'

            - name: Update api.json metadata
              run: |
                python -m pip install --upgrade pip
                python -m pip install OZI
                ozi -i | jq --compact-output > api.json

            - name: Commit api.json changes
              continue-on-error: true
              run: |
                git config --global user.name 'OZI-Project'
                git config --global user.email 'OZI-Project@users.noreply.github.com'
                git commit -am "API endpoint updated"
                git push
