on:
    schedule:
      - cron: '0 0 1 * *'
    workflow_dispatch:
    push:
      paths:
        - .api/*

permissions:
  contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:

            - uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
              with:
                egress-policy: audit

            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

            - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
              with:
               python-version: '3.12'

            - run: python -m pip install -r .api/requirements.txt

            - name: Update api.json metadata
              run: echo "value=$(ozi -i | jq --compact-output)" >> $GITHUB_OUTPUT
              id: api

            - run: echo $API > api.json
              if: steps.api.outputs.value != ''
              env:
                  API: ${{ steps.api.outputs.value }}

            - name: Commit api.json changes
              continue-on-error: true
              run: |
                git config --global user.name 'OZI-Project'
                git config --global user.email 'OZI-Project@users.noreply.github.com'
                git commit -am "API endpoint updated"
                git push
