on:
    schedule:
      - cron: '0 0 * * 0,1,2,3,4,5,6'
    workflow_dispatch:

permissions:
  contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:

            - name: Harden Runner
              uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
              with:
                egress-policy: audit

            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
              with:
               python-version: '3.12'

            - name: Update api.json metadata
              run: |
                python -m pip install --upgrade pip
                python -m pip install OZI
                ozi -i | jq --compact-output > api.json

            - name: Commit api.json changes
              continue-on-error: true
              run: |
                git config --global user.name 'OZI-Project'
                git config --global user.email 'OZI-Project@users.noreply.github.com'
                git commit -am "API endpoint updated"
                git push
